### ISSUE TITLE
Get error running it

### ISSUE THREAD

**Issue by nikivdev** [trietsch/alfred-bluetooth-connector#3] opened 2019-01-04 21:43 UTC
Get this in debugger when trying to use the workflow.

```
XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 64.)'. Row 2, Col 6: 'XML declaration allowed only at the start of the document' in XML:
```

**Comment by trietsch** [comment] 2019-01-04 22:04
Could you dump the result of:

`/usr/libexec/PlistBuddy -c "print :0:_items:0:device_title" /dev/stdin <<<
$(system_profiler SPBluetoothDataType -xml)`

Op vr 4 jan. 2019 22:43 schreef Nikita Voloboev <notifications@github.com:

**Comment by trietsch** [comment] 2019-01-04 22:04
Could you dump the result of:

`/usr/libexec/PlistBuddy -c "print :0:_items:0:device_title" /dev/stdin <<< $(system_profiler SPBluetoothDataType -xml)`

**Comment by nikivdev** [comment] 2019-01-06 13:51
```
Array {
    Dict {
        WH-1000XM3 = Dict {
            device_manufacturer = Cambridge Silicon Radio (0x7, 0x328E)
            device_minorClassOfDevice_string = Headset
            device_role = attrib_master
            device_services = Wireless iAP, Headset, CSR GAIA‚Ñ¢, AudioWear, Hands-Free unit, AudioWear Voice
            device_isconnected = attrib_Yes
            device_supportsEDR = attrib_Yes
            device_isconfigured = attrib_Yes
            device_majorClassOfDevice_string = Audio
            device_supportsESCO = attrib_Yes
            device_interval = 0 ms
            device_addr = CC-98-8B-1B-BF-11
            device_ConnectionMode = attrib_active_mode
            device_productID = 0x0CD3
            device_supportsSSP = attrib_Yes
            device_classOfDevice = 0x04 0x01 0x240404
            device_vendorID = 0x054C
            device_fw_version = 0x0200
            device_RSSI = -49
            device_ispaired = attrib_Yes
        }
    }
    Dict {
        Nikita’s AirPods = Dict {
            device_manufacturer = Apple (0x6, 0x03)
            device_supportsEDR = attrib_Yes
            device_supportsESCO = attrib_Yes
            device_services = Handsfree, Wireless iAP, AVRCP Controller, Audio Sink, AVRCP Target, AAP Server
            device_isconnected = attrib_No
            device_isconfigured = attrib_Yes
            device_majorClassOfDevice_string = Audio
            device_addr = 74-9E-AF-CE-B7-8F
            device_productID = 0x2002
            device_supportsSSP = attrib_Yes
            device_vendorID = 0x004C
            device_classOfDevice = 0x04 0x06 0x240418
            device_fw_version = 0x0372
            device_ispaired = attrib_Yes
            device_minorClassOfDevice_string = Headphones
        }
    }
    Dict {
        Nikita’s Apple Watch = Dict {
            device_ispaired = attrib_No
            device_addr = F8-6F-C1-02-91-96
            device_classOfDevice = 0x00 0x00 0x0000
            device_isconnected = attrib_No
            device_isconfigured = attrib_Yes
            device_majorClassOfDevice_string = Miscellaneous
            device_manufacturer = Apple (0x9, 0x2F00)
            device_minorClassOfDevice_string = Unknown
            device_services = 
        }
    }
    Dict {
        iPad = Dict {
            device_ispaired = attrib_No
            device_addr = 4C-56-9D-67-0F-FF
            device_classOfDevice = 0x00 0x00 0x0000
            device_isconnected = attrib_No
            device_isconfigured = attrib_Yes
            device_majorClassOfDevice_string = Miscellaneous
            device_manufacturer = Broadcom (0x9, 0x4307)
            device_minorClassOfDevice_string = Unknown
            device_services = 
        }
    }
    Dict {
        Nikita’s iPhone = Dict {
            device_ispaired = attrib_No
            device_addr = 38-53-9C-1B-81-59
            device_classOfDevice = 0x00 0x00 0x0000
            device_isconnected = attrib_No
            device_isconfigured = attrib_Yes
            device_majorClassOfDevice_string = Miscellaneous
            device_minorClassOfDevice_string = Unknown
            device_services = 
        }
    }
}
```

**Comment by trietsch** [comment] 2019-01-07 07:24
I've checked whether the problem is in the parsing and extraction of the device information, though that doesn't seem the issue (https://regex101.com/r/rcoH0n/1). The result of `normalized_devices` is:

`[{'address': 'CC-98-8B-1B-BF-11', 'name_connected': 'WH-1000XM3 [Connected]'}, {'address': '74-9E-AF-CE-B7-8F', 'name_connected': 'Nikita's AirPods [Disconnected]'}, {'address': 'F8-6F-C1-02-91-96', 'name_connected': 'Nikita's Apple Watch [Disconnected]'}, {'address': '4C-56-9D-67-0F-FF', 'name_connected': 'iPad [Disconnected]'}, {'address': '38-53-9C-1B-81-59', 'name_connected': 'Nikita's iPhone [Disconnected]'}]`

Could you show the contents of the log file (`~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/nl.robintrietsch.bluetooth/nl.robintrietsch.bluetooth.log`)? Maybe that'll give some more insight.

**Comment by nikivdev** [comment] 2019-01-10 12:41
> show the contents of the log file

```xml
22:42:52 workflow.py:2334 INFO     checking for update ...
22:42:52 update.py:312 INFO     retrieving releases: trietsch/alfred-bluetooth-connector
22:42:52 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2067, in run
    func(self)
  File "list_bluetooth_devices.py", line 70, in main
    wf.send_feedback()
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2176, in send_feedback
    sys.stdout.write(ET.tostring(root).encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
22:42:53 update.py:355 INFO     3 releases for trietsch/alfred-bluetooth-connector
22:42:58 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2067, in run
    func(self)
  File "list_bluetooth_devices.py", line 70, in main
    wf.send_feedback()
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2176, in send_feedback
    sys.stdout.write(ET.tostring(root).encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
22:43:05 workflow.py:2055 DEBUG    ---------- Bluetooth Device Connector (0.1.2) ----------
22:43:05 workflow.py:1462 DEBUG    reading settings from /Users/nikivi/Library/Application Support/Alfred 3/Workflow Data/nl.robintrietsch.bluetooth/settings.json
22:43:05 workflow.py:2339 DEBUG    update check not due
22:43:05 workflow.py:1689 DEBUG    loading cached data: /Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/nl.robintrietsch.bluetooth/__workflow_update_status.cpickle
22:43:05 workflow.py:2269 DEBUG    update_data: {u'available': False}
22:43:06 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2067, in run
    func(self)
  File "list_bluetooth_devices.py", line 70, in main
    wf.send_feedback()
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2176, in send_feedback
    sys.stdout.write(ET.tostring(root).encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
22:43:06 workflow.py:2097 DEBUG    ---------- finished in 0.242s ----------
14:51:34 workflow.py:2334 INFO     checking for update ...
14:51:34 update.py:312 INFO     retrieving releases: trietsch/alfred-bluetooth-connector
14:51:34 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.65232535-C1C5-4316-A933-E332D5E212ED/workflow/workflow.py", line 2067, in run
    func(self)
  File "list_bluetooth_devices.py", line 70, in main
    wf.send_feedback()
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.65232535-C1C5-4316-A933-E332D5E212ED/workflow/workflow.py", line 2176, in send_feedback
    sys.stdout.write(ET.tostring(root).encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
14:51:34 update.py:355 INFO     3 releases for trietsch/alfred-bluetooth-connector
13:40:32 workflow.py:2334 INFO     checking for update ...
13:40:32 update.py:312 INFO     retrieving releases: trietsch/alfred-bluetooth-connector
13:40:32 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C42C24-4077-4E34-A2C0-9D65D7A6B06C/workflow/workflow.py", line 2067, in run
    func(self)
  File "list_bluetooth_devices.py", line 70, in main
    wf.send_feedback()
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C42C24-4077-4E34-A2C0-9D65D7A6B06C/workflow/workflow.py", line 2176, in send_feedback
    sys.stdout.write(ET.tostring(root).encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
13:40:33 update.py:355 INFO     3 releases for trietsch/alfred-bluetooth-connector
```

**Comment by waynez** [comment] 2019-01-18 02:11
> > show the contents of the log file
> 
> ```
> 22:42:52 workflow.py:2334 INFO     checking for update ...
> 22:42:52 update.py:312 INFO     retrieving releases: trietsch/alfred-bluetooth-connector
> 22:42:52 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> Traceback (most recent call last):
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2067, in run
>     func(self)
>   File "list_bluetooth_devices.py", line 70, in main
>     wf.send_feedback()
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2176, in send_feedback
>     sys.stdout.write(ET.tostring(root).encode('utf-8'))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
>     ElementTree(element).write(file, encoding, method=method)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
>     serialize(write, self._root, encoding, qnames, namespaces)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
>     write(_escape_cdata(text, encoding))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
>     return text.encode(encoding, "xmlcharrefreplace")
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> 22:42:53 update.py:355 INFO     3 releases for trietsch/alfred-bluetooth-connector
> 22:42:58 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> Traceback (most recent call last):
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2067, in run
>     func(self)
>   File "list_bluetooth_devices.py", line 70, in main
>     wf.send_feedback()
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2176, in send_feedback
>     sys.stdout.write(ET.tostring(root).encode('utf-8'))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
>     ElementTree(element).write(file, encoding, method=method)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
>     serialize(write, self._root, encoding, qnames, namespaces)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
>     write(_escape_cdata(text, encoding))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
>     return text.encode(encoding, "xmlcharrefreplace")
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> 22:43:05 workflow.py:2055 DEBUG    ---------- Bluetooth Device Connector (0.1.2) ----------
> 22:43:05 workflow.py:1462 DEBUG    reading settings from /Users/nikivi/Library/Application Support/Alfred 3/Workflow Data/nl.robintrietsch.bluetooth/settings.json
> 22:43:05 workflow.py:2339 DEBUG    update check not due
> 22:43:05 workflow.py:1689 DEBUG    loading cached data: /Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/nl.robintrietsch.bluetooth/__workflow_update_status.cpickle
> 22:43:05 workflow.py:2269 DEBUG    update_data: {u'available': False}
> 22:43:06 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> Traceback (most recent call last):
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2067, in run
>     func(self)
>   File "list_bluetooth_devices.py", line 70, in main
>     wf.send_feedback()
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C2AE97C1-70E3-46A9-80DA-84404AA99090/workflow/workflow.py", line 2176, in send_feedback
>     sys.stdout.write(ET.tostring(root).encode('utf-8'))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
>     ElementTree(element).write(file, encoding, method=method)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
>     serialize(write, self._root, encoding, qnames, namespaces)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
>     write(_escape_cdata(text, encoding))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
>     return text.encode(encoding, "xmlcharrefreplace")
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> 22:43:06 workflow.py:2097 DEBUG    ---------- finished in 0.242s ----------
> 14:51:34 workflow.py:2334 INFO     checking for update ...
> 14:51:34 update.py:312 INFO     retrieving releases: trietsch/alfred-bluetooth-connector
> 14:51:34 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> Traceback (most recent call last):
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.65232535-C1C5-4316-A933-E332D5E212ED/workflow/workflow.py", line 2067, in run
>     func(self)
>   File "list_bluetooth_devices.py", line 70, in main
>     wf.send_feedback()
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.65232535-C1C5-4316-A933-E332D5E212ED/workflow/workflow.py", line 2176, in send_feedback
>     sys.stdout.write(ET.tostring(root).encode('utf-8'))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
>     ElementTree(element).write(file, encoding, method=method)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
>     serialize(write, self._root, encoding, qnames, namespaces)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
>     write(_escape_cdata(text, encoding))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
>     return text.encode(encoding, "xmlcharrefreplace")
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> 14:51:34 update.py:355 INFO     3 releases for trietsch/alfred-bluetooth-connector
> 13:40:32 workflow.py:2334 INFO     checking for update ...
> 13:40:32 update.py:312 INFO     retrieving releases: trietsch/alfred-bluetooth-connector
> 13:40:32 workflow.py:2074 ERROR    'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> Traceback (most recent call last):
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C42C24-4077-4E34-A2C0-9D65D7A6B06C/workflow/workflow.py", line 2067, in run
>     func(self)
>   File "list_bluetooth_devices.py", line 70, in main
>     wf.send_feedback()
>   File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C42C24-4077-4E34-A2C0-9D65D7A6B06C/workflow/workflow.py", line 2176, in send_feedback
>     sys.stdout.write(ET.tostring(root).encode('utf-8'))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
>     ElementTree(element).write(file, encoding, method=method)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
>     serialize(write, self._root, encoding, qnames, namespaces)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
>     _serialize_xml(write, e, encoding, qnames, None)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
>     write(_escape_cdata(text, encoding))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
>     return text.encode(encoding, "xmlcharrefreplace")
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
> 13:40:33 update.py:355 INFO     3 releases for trietsch/alfred-bluetooth-connector
> ```

I have the exact same issue. Do we have any update?

**Comment by trietsch** [comment] 2019-01-18 07:28
Seems it got something to do with unicode. I'll look into it asap.

**Comment by datenreisender** [comment] 2019-03-19 10:47
Same here: Does not run and has "'ascii' codec can't decode byte …" in the debugger (and also when running `./list_bluetooth_devices.py` manually).

I had a Bluetooth device with a non ascii character in it, but renaming it did not help.

Any idea, how I can assist you in this?

**Comment by trietsch** [comment] 2019-03-19 10:50
@datenreisender sorry for not responding here sooner. Together with another GitHub user that also created a bluetooth workflow, we've merged our work into [tilmanginzel/alfred-bluetooth-workflow](https://github.com/tilmanginzel/alfred-bluetooth-workflow).
Please install this one, it should work for you :)

**Closed as completed by trietsch** 2019-03-19 10:50 UTC

**Comment by datenreisender** [comment] 2019-03-19 10:52
Nice, thanks!
